---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  estate: "%{hiera('estate')}"
  aws_profile: "%{hiera('aws_admin_profile')}"
  test_users:
    - test1
    - test2
  pgp_key_for_secrets: "%{hiera('pgp_key_for_secrets')}"

state:
  type: local

inspec:
  aws_profile:
    default: "%{hiera('aws_admin_profile')}"
    unprivileged: "%{hiera('aws_unprivileged_profile')}"
