---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  estate: "%{hiera('estate')}"
  aws_profile: "%{hiera('aws_admin_profile')}"
  test_users:
    - test1
    - test2

state:
  type: local
