---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  estate: "%{hiera('estate')}"
  aws_profile: "%{hiera('aws_profile')}"
  api_users: "%{hiera('api_users')}"
  pgp_key_for_secrets: "%{hiera('pgp_key_for_secrets')}"
  assume_role_arn: "%{hiera('admin_role_arn')}"

state:
  type: local
